// <auto-generated />
namespace _5204_Passion_Project_n01442368_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20210209 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210209));
        
        string IMigrationMetadata.Id
        {
            get { return "202102100112193_2021-02-09"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
