// <auto-generated />
namespace _5204_Passion_Project_n01442368_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifieddisplayname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifieddisplayname));
        
        string IMigrationMetadata.Id
        {
            get { return "202102190149379_modified display name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
